### ISSUE TITLE
Generování Badges s danými informacemi


### ISSUE THREAD

**Issue by VojtaStanek** [SkautDevs/kissj#10]

**Comment by tomtomklima** [comment]
Jde generovat z exportů, closing

**Comment by tomtomklima** [comment]
But actually.... generovat bychom je mohli :D

Ideálně podobný princip jako se generují průvodky. Funkce:
 - před generováním zvolit, pro jaké role se mají badges generovat
 - do PDF
 - základní velikost je A6, tedy generovat 4 badges na A4
 - do generování vstupují všechny dostupné informace podle content arbiteru
 - čisté HTML pouze vypisuje informace a nijak neřadí/neformátuje
 - CSS formátuje a je přetížitelné pro každý EventType zvlášť
 - potřeba vymyslet, jak s generováním badges pro hosty/návštěvníky, které jsou generické

**Comment by tomtomklima** [comment]
na stagingu, zavírám
