### ISSUE TITLE
Roadmap 2022

### ISSUE THREAD

**Issue by vojtechmares** [SkautDevs/kissj#103]
# Roadmap 2022

## Milestones

- [Redesign with TailwindCSS](https://github.com/SkautDevs/kissj/milestone/4)

**Comment by tomtomklima** [comment]
@vojtechmares budeš dodělávat? Jinak bych to zavřel a nechal to na náhodných groomovacích sessions

**Comment by vojtechmares** [comment]
Mám to v plánu, ale chtěl jsem se o tom společně pobavit, co chceme v 2022 od KISSJ. Asi to můžeme zavřít ale a jet případně jen milestones.
