### ISSUE TITLE
Drop old deploy/dev with SQLite

### ISSUE THREAD

**Issue by vojtechmares** [SkautDevs/kissj#104]
Refactored to use PostgreSQL on local.

TODO:
 - delete `deploy/dev` and clean up `Makefile`

**Comment by tomtomklima** [comment]
to bych si klidně vzal @vojtechmares? Stejně to stojí na mě, až se mentálně rozloučím s sqlite (:

**Comment by vojtechmares** [comment]
Ok, až se Ti bude chtít, tak to promázni.

**Comment by tomtomklima** [comment]
@vojtechmares promáznuto v kódu, klidně uprav make pls
@kaplan-michael pls dodej xdebug, abych to nemusel spouštět ručně (v produkci je to OK, protože bude vypnutý ;)

**Comment by tomtomklima** [comment]
smazáno
