### ISSUE TITLE
Wrong locale button /login

### ISSUE THREAD

**Issue by misakstvanu** [SkautDevs/kissj#115]
Na _en_ jazykové verzi chybí možnost změny do _cs_:
There is no option to switch to _cs_ locale on _en_ version:

![image](https://user-images.githubusercontent.com/42741294/144948667-786e6d46-e5df-4517-a29a-4a4cfc462cda.png)

**Comment by tomtomklima** [comment]
Díky za povšimnutí, nicméně toto je vlastnost mezinárodní akce - na jiných akcích (třeba na https://kissj.net/v2/event/navigamus22/login) běží vše v cajku.
