### ISSUE TITLE
enable multiple bank connections

### ISSUE THREAD

**Issue by vojtechmares** [SkautDevs/kissj#118]
enabler for multiple bank connections, not only Fio

- [x] backport https://github.com/SkautDevs/kissj/commit/4813b99e1b75d3dfd450c0875eec41a9bd0b8cb6
- [x] refactor `IBankPaymentService` into abstract and move methods `setBankPaymentPaired()` and `setBankPaymentUnrelated()` there
- [x] set usage of abstract class instead of `FioBankPaymentService` in all app
- [x] remove deprecated `/setBreakpointFromRoute` route with all connected unused methods
- [x] use bank_id from DB `event` table, refactor it into more verbose one - `bankSlug` or something similar and make choosing service dynamic (and still keep only one concrete Fio service)

**Comment by tomtomklima** [comment]
Co znamená toto?

**Comment by vojtechmares** [comment]
@tomtomklima bavili jsme se o tomhle, že tam je hezký commit co se týče plateb a bylo by fajn jej backportovat. Už je to hodně staré a jsou tam nějaké conflicty, takže to chce na to v klidu sednout a projít

**Comment by tomtomklima** [comment]
done
