### ISSUE TITLE
Rozdělení platby na vícero plateb (splátkový kalendář)

### ISSUE THREAD

**Issue by vojtechmares** [SkautDevs/kissj#119]
### Motivace

Jamboree má cenu kolem 42 tisíc, nechceme po lidech toto platit najednou, přecijen by to velmi narušilo cashflow rodiny a popř. sociálně slabší rodiny ->  chceme splátkový kalendář

### Požadavky

- výše plateb se nastaví ručně v administraci eventu
- platba generuje email
- platba se automaticky páruje

**Comment by tomtomklima** [comment]
done
