### ISSUE TITLE
splátkový kalendář pro více plateb pro rozložení vícero plateb

### ISSUE THREAD

**Issue by vojtechmares** [SkautDevs/kissj#126]
- první platba potvrdí registraci
- v administraci možnost konfigurovat N plateb o M částce
- datum splatnosti pro každou platbu zvlášť a datum vystavení
- platba se dá editovat do momentu, dokud není vystavena, v ten moment se platba uzavírá (nelze ji dál upravovat)

**Comment by tomtomklima** [comment]
máme vyřešené přes generování vícero plateb, closing
