### ISSUE TITLE
Účastníci v patrole si sami spravují nahrané soubory

### ISSUE THREAD

**Issue by vojtechmares** [SkautDevs/kissj#129]
- účastníci v patrole mají přístup do systému a mohou nahrávat jednotlivé soubory, které požadujeme
- v administraci možnost přidávat další dokumenty

nový dokument v administraci pro skupinu (IST, účastník, VJO) -> mail o novém dokumentu -> upomínkování dokud není soubor nahrán (?)

**Comment by Radar4** [comment]
Pokud by systém uměl automaticky upomínkovat na nenahraný soubor, bude to pecka..ušetří nám pár starostí Případně potvrdit úspěšné nahrání.

**Comment by tomtomklima** [comment]
funguje v troops, done
