### ISSUE TITLE
Management účastníků v troopech

### ISSUE THREAD

**Issue by vojtechmares** [SkautDevs/kissj#130]
- v administraci je možné spravovat účastníky v patrolách

**Comment by tomtomklima** [comment]
je toto ještě aktuální @vojtechmares?

**Comment by vojtechmares** [comment]
Už se to řeší excelem... ale kdyby to bylo, bylo by to nice to have (stejně to do budoucna dává smysl mít).

Ale jinak je to cca o 3 měsíce pozdě.

**Comment by tomtomklima** [comment]
Takže sice necháváme, ale necháme priority:low?

**Comment by tomtomklima** [comment]
done
