### ISSUE TITLE
přidat do exportu datum, kdy se účastník zaregistroval (kdy se mu vytvořil účet)

### ISSUE THREAD

**Issue by vojtechmares** [SkautDevs/kissj#146]
ideální by bylo, kdy si uzamkl registraci, ale takové datum nemáme AFAIK

**Comment by tomtomklima** [comment]
neviadí, přiděláme. Asi i s časem zaplacení a schválení, ať to máme pohromadě

**Comment by vojtechmares** [comment]
Done
