### ISSUE TITLE
Instalace na Lebedě

### ISSUE THREAD

**Issue by lharaga** [SkautDevs/kissj#148]
Ahoj,

existuje návod, jak rozjet tento projekt na Lebedě?

Rád bych v readme či jinde viděl návod na rozjetí jinak, než přes docker - je-li to možné.

Děkuji.
Luky

**Comment by tomtomklima** [comment]
Bohužel. Z historických důvodů to šlo, potom ale přestal server stíhat výkonově i nástroji. Nicméně server https://kissj.net/ umožňuje založit více akcí. Ozvi se napřímo a vyřešíme (:
