### ISSUE TITLE
Plugin pro poskytování možnosti výběru programů

### ISSUE THREAD

**Issue by VojtaStanek** [SkautDevs/kissj#15]

**Comment by paaton** [comment]
# Představa pro Obrok 24
### nové event properties: 
- programsGformUrl (string)
- programRegistrationClosedDate (Datetime)
- userProgramPublishDate (Datetime)

### nové participant properties:
- programRegistrationStatus (int?) [form_unfilled,  form_filled, program_published], 
- userPublishedProgram (arr) [eventType, nebo translatable defined programy, počet okolo 30, popř. jen strings]

## Funkce:

### `programRegistrationStatus == form_unfilled $$ user->status == payed: $$ programRegistrationClosedDate > Datetime.now`
- v participant dashboard ukazovat tlačítko "vyplnit formulář na dotazníky".
- odkazuje na formulář ve formátu `event->programsGformUrl + participant->tieCode`, např. _"https://docs.google.com/forms/d/e/bnfhu4Ajbe7iw/viewform?entry.2082059253=KFPGH"_
- po vyplnění formuláře pošle gform POST req. na nově otevřenou cestu, např. _"/v2/event/obrok24/ProgramsFormSubmit",_ - request head obsahuje auth. s preshared klíčem (kde ukládat?), req. body ve formátu  `{"userTieCode":participant->tieCode}`
- pokud existuje participant s provided userTieCode, nastaví jeho status na form_filled

### `user->status == payed: $$ programRegistrationClosedDate < Datetime.now > userProgramPublishDate`
- v participant dashboard text o konci registrace programů v event->programRegistrationClosedDate

### `programRegistrationStatus == form_filled $$ user->status == payed: $$ userProgramPublishDate > Datetime.now`
- v participant dashboard seznam programů, které byly účastníkovi vygenerovány a doplňující text translatable vysvětlující jak byly programy vybrány.

## Dodatek
- účastníci vyplní form, my poté z formu vytvoříme každému program na míru a ten nahrajeme do kissj

## Admin dashboard
- pokud zvládneme v payed_participants view zobrazovat jejich programRegistrationStatus, bude to fajn.

**Comment by tomtomklima** [comment]
uděláme v rámci https://github.com/SkautDevs/kissj/issues/223
