### ISSUE TITLE
Některé platby se nepropisují do kissj

### ISSUE THREAD

**Issue by vprouza** [SkautDevs/kissj#167]
Na společným účtu pro cej a wsj je platba, která není vidět v seznamu plateb u cej. Konkrétně jde o platbu, která má v bankpayment id 759 a existuje pouze pod event_id = 8. U CEJe se platba vůbec neobjeví.
Možná je takových plateb více, žádné další případy jsem ale nenašel.

**Comment by tomtomklima** [comment]
Sunny: Fixnuto přidáním bank breakpointu do databáze per event, zatím v extra branchi. Done by Sunny :muscle:

**Comment by tomtomklima** [comment]
fixnuto, do budoucna v kódu a do minulosti ručně úpravou v DB
