### ISSUE TITLE
email sending fails on test event

### ISSUE THREAD

**Issue by kaplan-michael** [SkautDevs/kissj#188]
on test event, emails can't be sent and an error is displayed. WAE on other events

**Comment by tomtomklima** [comment]
na produ i na localu nezreplikováno

**Comment by kaplan-michael** [comment]
![image](https://user-images.githubusercontent.com/16418072/232572386-391a6742-1eab-4e3e-b3d1-a91871a07099.png)

deje se to jen na test-eventu a pokud si vzpominam, tak byl issue s event typem.

**Comment by tomtomklima** [comment]
@kaplan-michael vyzkoušel jsem i ten, i na produ, i na localhostu

**Comment by tomtomklima** [comment]
fixed
