### ISSUE TITLE
Zobrazovat pole a zapnout "required" pro uložení PDF a vypsání zákonného zástupce na akci, jen když účastník vyplní věk 18-

### ISSUE THREAD

**Issue by tomtomklima** [SkautDevs/kissj#196]

**Comment by paaton** [comment]
Věk 18- je počítaný z datumu začátku akce, ne z data zadávání registrace.

_Může mi někdo na toto hodit assign prosím?_

**Comment by tomtomklima** [comment]
frajeřinka by byla vyplňovat větičku (k datu začátku aktce ti bude 17-/18+ let), ale to už asi nechám na tobě
