### ISSUE TITLE
Import účastníků (IST only zatím stačí) z excelu administrace

### ISSUE THREAD

**Issue by tomtomklima** [SkautDevs/kissj#252]
Povoli jednak nahrání technických týmů z tabulky (typicky SZT + SOS), nebo exportu ze SRS (potřeba dodat vzorek exportu)

- [x] vytáhnout ze SRS sjetinu v CSV se všemi informacemi na jedné kupě (všechno v jedné tabulce plspls) @paaton 
- [x] nakódit import z CSV do kissj (nedublovat lidi) @tomtomklima

**Comment by paaton** [comment]
Ahoj,
myslím, že tam budeme mít nějaké lidi, co mají vytvořenou a někdy i uzamčenou skupinu, nicméně nevešli se, tak se zaregistrovali jako servis, tak to je třeba pořešit.

A vychází z toho další otázka, co když se tito lidi budou chtít registrovat jako servis, ale už jsou locked state účastníci?

**Comment by tomtomklima** [comment]
když jsou locked, budou mít platbu. Když dlouho nezaplatí, měli bychom je zpět odemknout s tím, že dlouho nezaplatili a tím se to vyřeší

**Comment by tomtomklima** [comment]
done
