### ISSUE TITLE
Při uzamykání účastníka a chybě "již je uzamčený" vracet info/warinig flash message místo #500

### ISSUE THREAD

**Issue by tomtomklima** [SkautDevs/kissj#270]

**Comment by paaton** [comment]
V kódu již funkční check na "již uzamknuto", opraveno při Issue #76 , stále je možné dosáhnout 500? jedná se o file [ParticipantService](src/Participant/ParticipantService.php) line 352

**Comment by tomtomklima** [comment]
Nejspíš ano, zavírám
