### ISSUE TITLE
Last-minute dodělávky na akci, zjména entry

### ISSUE THREAD

**Issue by tomtomklima** [SkautDevs/kissj#283]
Entry app
- [x] samostatný vstup pro leadery skupin
- [x] zablokovalt vstup pro celou skupinu když nebudou mít SFH všichni
- [x] filtr na vstoupení/nevstoupené
- [x] označit clearly vstoupené/nevstoupené

KISSJ
- [x] edit účastníka - buttonky vstup + unvstup
- [x] možnost vstupu bez SFH jednotlivci
- [ ] počty entry lidí na dashboard

NICE2HAVE
- [ ] možnost vstupu bez SFH skupiny
- [ ] možnost deregistrace
- [ ] přidat do exportu TIE code + skautis membership + entry date
- [ ] #284
- [ ] lepší a rychlejí - http://kissj.skauting.cz/showBearerTokenInput aby předvyplnil token, který přijde v GETu

**Comment by paaton** [comment]
zaměřím se na funkční Auth(asi přes JWT), pak před akcí můžeme řešit zbytek

**Comment by tomtomklima** [comment]
done potřebné
