### ISSUE TITLE
Vystavit v3 API pro schvalování účastníků

### ISSUE THREAD

**Issue by tomtomklima** [SkautDevs/kissj#300]
Příprava na JS frontend

**Comment by tomtomklima** [comment]
Done - nasazeno na staging

Routa pro toto API je `POST:/v3/event/{eventName}admin/approving/approveParticipant/{participantId}` - vrací 200 s JSON položkou `userStatus`když je succes, případně 400 pro fail s JSON položkami `translationKey` a `translationMessage`. 

Dotaz na @danielchodusov  - jak si to můžeme předávat? Moje preferované varianta by byla generovaná dokumentace (minimálně pro v3) - existuje nějaký systém pro generování dokumentace, který bys doporučil?

**Comment by danielchodusov** [comment]
@tomtomklima nám se osvědčilo pro automatické generování https://swagger.io/tools/swagger-ui/ pro REST API (jak to pak vypadá je vidět třeba zde https://petstore3.swagger.io)
