### ISSUE TITLE
Dockerizace

### ISSUE THREAD

**Issue by tomtomklima** [SkautDevs/kissj#36]

**Comment by tomtomklima** [comment]
Ve větvi https://github.com/SkautDevs/kissj/tree/docker - potřeba fixnout `connection was reset` error

**Comment by racinmat** [comment]
fixnuto, ale vypadá to, že je tam další problém, asi něco s https. Pokud používáš HTTPS, musíš si kromě portu 80 namapovat i port 443.

**Comment by tomtomklima** [comment]
done
