### ISSUE TITLE
Just small documentation improvement

### ISSUE THREAD

**Issue by skifahrer** [SkautDevs/kissj#4]
Hi Guys,
I used your system, it is great. I would like to recommend to add this command in installation instructions `sqlite3 db.sqlite < sql/init.sql` You will made it simpler for most users :-)

**Comment by tomtomklima** [comment]
Hi, thanks for your suggestion - we definitely could add this instruction

**Comment by tomtomklima** [comment]
Implemented. Btw @skifahrer on what event did you use kissj?

**Comment by skifahrer** [comment]
Hi @tomtomklima we use it for registration to the central european jamboree 2018 in Hungary
