### ISSUE TITLE
Fixnout špatnou barvu textu (z modré na bílou) v tlačítku v mailu

### ISSUE THREAD

**Issue by tomtomklima** [SkautDevs/kissj#52]
Gmail:

![image](https://user-images.githubusercontent.com/8727413/57034623-51f98000-6c50-11e9-87ea-023633fa41c2.png)

**Comment by fialazd2** [comment]
Týká se pouze (možná nejen pouze) gmailového prohlížeče, který text k odkazům "<a href..." automaticky zobrazuje modře. Zatím nejlepší řešení mi přijde použít tag <font color="white"> uvnitř tagu <a>.

Nicméně lze vyřešit např. i pomocí inline stylování, což mi přijde jako horší řešení.

**Comment by tomtomklima** [comment]
fixed by d7f056
