### ISSUE TITLE
Feature Toggles - Možnost zapínání a vypínání features, které chceme/nechceme

### ISSUE THREAD

**Issue by Cactucs** [SkautDevs/kissj#8]

**Comment by tomtomklima** [comment]
Pomocí pattern Mediator/Observer? (osobně jsem pro mediator, je jednodušší, mnohem používanější a víc se hodí na insert code)
Použít třeba Event Dispatcher od Symphony? Nebo si to napsat sami, je to na pár řádků

**Comment by tomtomklima** [comment]
implementuje se
