### ISSUE TITLE
Při registraci zobrazovat datum narození "česky", lepší date picker?

### ISSUE THREAD

**Issue by vprouza** [SkautDevs/kissj#94]

**Comment by vprouza** [comment]
Případně podle nastaveného jazyka

**Comment by tomtomklima** [comment]
je to podle local jazyka, je to nativní funkce browseru

**Comment by vprouza** [comment]
![image](https://user-images.githubusercontent.com/51821713/140441859-f358a518-9111-434e-b261-9b6443a3ec05.png)
Myslím již ve formuláři, lokalizace systému i browseru nastaven na česko
![image](https://user-images.githubusercontent.com/51821713/140441905-35d0a723-d9c3-42b7-89be-cc8722398bd2.png)

**Comment by tomtomklima** [comment]
Jo, někde máš nastavenou angličtinu - když jsem to studoval, tak browsery si to dělají, jak chtějí a kašlou na nastavení systému i všeho dalšího. Zkontroluj browser setting, možná jiný browser - museli bychom vyřešit nějakým JS datepickerem
