### ISSUE TITLE
vytvořit překladatelné placeholders pro všecny políčka+role ve vyplňování detailů

### ISSUE THREAD

**Issue by tomtomklima** [SkautDevs/kissj#98]

**Comment by tomtomklima** [comment]
zejména ve file `src/Templates/translatable/widgets/changeDetails.twig` a v překladech

**Comment by tomtomklima** [comment]
a tady by ses mohl taky podívat @paaton což?

**Comment by paaton** [comment]
> a tady by ses mohl taky podívat @paaton což?

Záleží na deadline, já teď do 15.května jedu skoro full-time NSJ. Ale dám si to do TODO. Díky.

**Comment by paaton** [comment]
done
